name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Building
        run: |
          yarn
          yarn build
      - name: Move build to remote
        uses: appleboy/scp-action@master
        with:
          source: ".output, .nuxt"
          target: "/var/www/bokoblin-site-n3/"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          overwrite: true
      - name: Deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            # Pull and build new version
            export PATH="$PATH:/home/ubuntu/.nvm/versions/node/v16.19.0/bin"
            eval $(ssh-agent)
            ssh-add ~/.ssh/id_ecdsa
            cd /var/www/bokoblin-site-n3
            git checkout main
            git fetch --all
            git reset --hard origin/main
            yarn predev
            pm2 restart ecosystem.config.js --env production
